llm:
  config:
    default:
      _target_: llm_chatbot_api.api.schemas.ModelConfig
      model_name: "accounts/fireworks/models/llama-v3-70b-instruct"
      chat_history_limit: 10
      max_tokens: 2500
      temperature: 0.7
      provider: "fireworksai"
image_model:
  config:
    default:
      _target_: llm_chatbot_api.api.schemas.ImageModelConfig
      model_name: "dall-e-3"
      provider: "OpenAI"
      size: "1024x1024"
      n: 1
      quality: "standard"

api:
    version: "0.1.0"
    title: "LLM Chatbot API"
    description: "API for interaction with llm chatbot"
    host: "0.0.0.0"
    port: 8000